name: Publish
on:
  push:
    branches:
      - main

jobs:
  publish-package:
    runs-on: ubuntu-22.04
    environment: release
    timeout-minutes: 10

    permissions:
      # Used to authenticate to PyPI via OIDC.
      # Used to sign the release's artifacts with sigstore-python.
      id-token: write
      # Used to attach signing artifacts to the published release.
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Install Poetry
        shell: bash
        run: pipx install poetry
      
      - uses: actions/setup-python@v5
        id: setup-python
        with:
          cache: 'poetry'
          cache-dependency-path: ${{ format('{0}/poetry.lock', github.workspace) }}
      
      - name: check poetry lock
        run: |
          poetry check --lock
          python --version
          poetry --version
        shell: bash
        working-directory: ${{ github.workspace }}
      
      - name: Create virtualenv and install dependencies
        shell: bash
        working-directory: ${{ github.workspace }}
        run: poetry install

      - name: Build Python package
        run: poetry build
      
      - name: Publish to PyPi
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          verbose: true
          print-hash: true
      
      - name: Sign published artifacts
        uses: sigstore/gh-action-sigstore-python@v2.1.0
        with:
          inputs: ./dist/*.tar.gz ./dist/*.whl
          release-signing-artifacts: true
